'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronDown, Clock3, Globe2, Link2, MapPin, Plus, Sparkles, Video, X } from 'lucide-react'
import { Button } from '@/components/ui/button'

type Role = 'teacher' | 'student'
type Day = { key: number; name: string; short: string; enabled: boolean; windows: string[] }

const initialDays: Day[] = [
  { key: 1, name: 'Monday', short: 'Mon', enabled: true, windows: ['09:00 AM – 12:00 PM', '01:00 PM – 05:00 PM'] },
  { key: 2, name: 'Tuesday', short: 'Tue', enabled: true, windows: ['09:00 AM – 12:00 PM', '01:00 PM – 05:00 PM'] },
  { key: 3, name: 'Wednesday', short: 'Wed', enabled: true, windows: ['09:00 AM – 12:00 PM', '01:00 PM – 05:00 PM'] },
  { key: 4, name: 'Thursday', short: 'Thu', enabled: true, windows: ['09:00 AM – 12:00 PM'] },
  { key: 5, name: 'Friday', short: 'Fri', enabled: true, windows: ['09:00 AM – 01:00 PM'] },
  { key: 6, name: 'Saturday', short: 'Sat', enabled: false, windows: ['10:00 AM – 01:00 PM'] },
  { key: 0, name: 'Sunday', short: 'Sun', enabled: false, windows: ['10:00 AM – 01:00 PM'] },
]
const slots = ['09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM', '01:00 PM', '01:30 PM', '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM']
const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

export function SchedulingModule({ profileName, initialRole = 'teacher' }: { profileName: string; initialRole?: Role }) {
  const [role, setRole] = useState<Role>(initialRole)
  const [days, setDays] = useState(initialDays)
  const [duration, setDuration] = useState('45 min')
  const [title, setTitle] = useState('Algebra Mentorship')
  const [selectedDate, setSelectedDate] = useState(new Date(2026, 8, 22))
  const [selectedSlot, setSelectedSlot] = useState<string | null>(null)
  const [confirmed, setConfirmed] = useState(false)
  const [showOverride, setShowOverride] = useState(false)
  const [monthOffset, setMonthOffset] = useState(0)
  const [studentName, setStudentName] = useState('')
  const [studentEmail, setStudentEmail] = useState('')

  const month = useMemo(() => new Date(2026, 8 + monthOffset, 1), [monthOffset])
  const calendarDays = useMemo(() => {
    const start = new Date(month.getFullYear(), month.getMonth(), 1).getDay()
    const total = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate()
    return [...Array(start).fill(null), ...Array.from({ length: total }, (_, i) => new Date(month.getFullYear(), month.getMonth(), i + 1))]
  }, [month])
  const activeDays = days.filter((day) => day.enabled)
  const selectedDay = days.find((day) => day.key === selectedDate.getDay())
  const available = Boolean(selectedDay?.enabled)

  function toggleDay(key: number) { setDays((current) => current.map((day) => day.key === key ? { ...day, enabled: !day.enabled } : day)) }
  function selectDate(date: Date) { setSelectedDate(date); setSelectedSlot(null); setConfirmed(false) }
  function formatDate(date: Date) { return date.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }) }

  return <main className="min-h-screen bg-[#f5f7fb] text-slate-950">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-4 px-4 py-4 sm:px-8"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-indigo-600 text-white"><CalendarDays /></div><div><p className="text-lg font-bold tracking-tight">Quanttoria</p><p className="text-xs text-slate-500">Scheduling workspace</p></div></div><div className="flex items-center gap-2 rounded-xl bg-slate-100 p-1" role="group" aria-label="Choose workspace"><button onClick={() => setRole('teacher')} className={`rounded-lg px-3 py-2 text-sm font-semibold transition ${role === 'teacher' ? 'bg-white text-indigo-700 shadow-sm' : 'text-slate-500'}`}>Teacher View</button><button onClick={() => setRole('student')} className={`rounded-lg px-3 py-2 text-sm font-semibold transition ${role === 'student' ? 'bg-white text-indigo-700 shadow-sm' : 'text-slate-500'}`}>Student View</button></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-sm font-semibold">{profileName}</p><p className="text-xs text-slate-500">{role === 'teacher' ? 'Teacher account' : 'Student account'}</p></div><div className="grid size-10 place-items-center rounded-full bg-indigo-100 font-bold text-indigo-700">{profileName.charAt(0)}</div></div></div></header>
    {role === 'teacher' ? <TeacherView days={days} duration={duration} title={title} setDuration={setDuration} setTitle={setTitle} toggleDay={toggleDay} activeDays={activeDays} showOverride={showOverride} setShowOverride={setShowOverride} /> : <StudentView month={month} monthOffset={monthOffset} setMonthOffset={setMonthOffset} calendarDays={calendarDays} selectedDate={selectedDate} selectDate={selectDate} selectedSlot={selectedSlot} setSelectedSlot={setSelectedSlot} available={available} selectedDay={selectedDay} duration={duration} title={title} confirmed={confirmed} setConfirmed={setConfirmed} studentName={studentName} setStudentName={setStudentName} studentEmail={studentEmail} setStudentEmail={setStudentEmail} formatDate={formatDate} />}
  </main>
}

function TeacherView({ days, duration, title, setDuration, setTitle, toggleDay, activeDays, showOverride, setShowOverride }: { days: Day[]; duration: string; title: string; setDuration: (value: string) => void; setTitle: (value: string) => void; toggleDay: (key: number) => void; activeDays: Day[]; showOverride: boolean; setShowOverride: (value: boolean) => void }) {
  return <div className="mx-auto max-w-[1440px] px-4 py-8 sm:px-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-indigo-600">Teacher workspace</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Manage your availability</h1><p className="mt-2 max-w-2xl text-slate-500">Set your recurring hours and give students an easy way to book time with you.</p></div><Button className="rounded-xl bg-indigo-600 hover:bg-indigo-700">Save changes</Button></div><div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]">
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Weekly hours</h2><p className="mt-1 text-sm text-slate-500">Recurring availability for every week</p></div><button className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-600"><Globe2 className="size-4" /> Eastern Time <ChevronDown className="size-4" /></button></div><div className="mt-6 divide-y divide-slate-100">{days.map((day) => <div key={day.key} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center"><button aria-label={`Toggle ${day.name}`} aria-pressed={day.enabled} onClick={() => toggleDay(day.key)} className={`relative h-6 w-11 shrink-0 rounded-full transition ${day.enabled ? 'bg-indigo-600' : 'bg-slate-200'}`}><span className={`absolute top-1 size-4 rounded-full bg-white shadow transition ${day.enabled ? 'left-6' : 'left-1'}`} /></button><div className="w-28 font-semibold">{day.name}</div><div className="flex flex-1 flex-wrap gap-2">{day.enabled ? day.windows.map((window) => <span key={window} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-medium"><Clock3 className="size-4 text-indigo-600" />{window}</span>) : <span className="py-2 text-sm text-slate-400">Unavailable</span>} {day.enabled && <button className="rounded-lg border border-dashed border-slate-300 px-3 py-2 text-sm font-semibold text-indigo-600 hover:bg-indigo-50"><Plus className="mr-1 inline size-4" />Add time</button>}</div></div>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-indigo-50 p-4 text-sm"><span className="font-semibold text-indigo-900">{activeDays.length} days available this week</span><span className="text-indigo-700">10 min buffer between sessions</span></div></section>
    <div className="flex flex-col gap-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold">Session type</h2><p className="mt-1 text-sm text-slate-500">What are students booking?</p><label className="mt-5 block text-sm font-semibold" htmlFor="session-title">Class title / subject</label><input id="session-title" value={title} onChange={(event) => setTitle(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" /><label className="mt-4 block text-sm font-semibold">Session duration</label><div className="mt-2 grid grid-cols-3 gap-2">{['30 min', '45 min', '60 min'].map((item) => <button key={item} onClick={() => setDuration(item)} className={`rounded-xl border py-2.5 text-sm font-semibold ${duration === item ? 'border-indigo-600 bg-indigo-50 text-indigo-700' : 'border-slate-200 text-slate-600'}`}>{item}</button>)}</div><label className="mt-4 block text-sm font-semibold" htmlFor="location">Location</label><button id="location" className="mt-2 flex w-full items-center justify-between rounded-xl border border-slate-200 px-3 py-2.5 text-left text-sm font-medium"><span className="flex items-center gap-2"><Video className="size-4 text-indigo-600" /> Zoom meeting</span><ChevronDown className="size-4" /></button></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Date overrides</h2><p className="mt-1 text-sm text-slate-500">Block vacations or one-off days</p></div><button onClick={() => setShowOverride(!showOverride)} className="rounded-lg border border-slate-200 p-2 text-slate-600"><Plus className="size-4" /></button></div>{showOverride && <div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-50 p-3"><input type="date" className="min-w-0 flex-1 rounded-lg border border-slate-200 bg-white p-2 text-sm" /><Button size="sm" className="bg-indigo-600">Block day</Button></div>}<div className="mt-5 flex items-center gap-3 rounded-xl border border-dashed border-slate-300 p-4 text-sm text-slate-500"><Sparkles className="size-5 text-indigo-500" /> No upcoming blocked days</div></section></div>
  </div></div>
}

function StudentView({ month, monthOffset, setMonthOffset, calendarDays, selectedDate, selectDate, selectedSlot, setSelectedSlot, available, selectedDay, duration, title, confirmed, setConfirmed, studentName, setStudentName, studentEmail, setStudentEmail, formatDate }: any) {
  return <div className="mx-auto max-w-[1440px] px-4 py-8 sm:px-8"><div className="mb-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-indigo-600">Book a session</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Find a time that works for you</h1><p className="mt-2 text-slate-500">Choose a date, pick a time, and you’re all set.</p></div><div className="grid overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm lg:grid-cols-[280px_1fr_280px]">
    <aside className="border-b border-slate-200 p-6 lg:border-b-0 lg:border-r"><div className="flex items-center gap-3"><div className="grid size-12 place-items-center rounded-full bg-indigo-100 text-lg font-bold text-indigo-700">A</div><div><p className="font-bold">Alex Morgan</p><p className="text-sm text-slate-500">Math tutor</p></div></div><div className="mt-8"><h2 className="text-2xl font-bold">{title}</h2><div className="mt-4 flex flex-col gap-3 text-sm text-slate-600"><span className="flex items-center gap-2"><Clock3 className="size-4 text-indigo-600" />{duration}</span><span className="flex items-center gap-2"><Video className="size-4 text-indigo-600" />Zoom meeting</span><span className="flex items-center gap-2"><Globe2 className="size-4 text-indigo-600" />Eastern Time</span></div></div><div className="mt-10 rounded-xl bg-indigo-50 p-4 text-sm leading-6 text-indigo-900">Select a date and time to book a private tutoring session.</div></aside>
    <section className="p-6 sm:p-8"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Select a date</h2><p className="mt-1 text-sm text-slate-500">Available dates are highlighted</p></div><div className="flex gap-1"><button aria-label="Previous month" onClick={() => setMonthOffset(monthOffset - 1)} className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft className="size-4" /></button><button aria-label="Next month" onClick={() => setMonthOffset(monthOffset + 1)} className="rounded-lg p-2 hover:bg-slate-100"><ArrowRight className="size-4" /></button></div></div><div className="mt-6 flex items-center justify-between"><h3 className="font-bold">{monthNames[month.getMonth()]} {month.getFullYear()}</h3><span className="text-xs font-semibold text-slate-400">All times local</span></div><div className="mt-4 grid grid-cols-7 gap-1 text-center text-xs font-semibold text-slate-400">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => <span key={day} className="py-2">{day}</span>)}{calendarDays.map((date: Date | null, index: number) => date ? <button key={date.toISOString()} onClick={() => selectDate(date)} className={`rounded-xl py-3 text-sm transition ${date.toDateString() === selectedDate.toDateString() ? 'bg-indigo-600 font-bold text-white shadow-md' : 'text-slate-700 hover:bg-indigo-50'} ${date.getDay() === 0 || date.getDay() === 6 ? 'text-slate-400' : ''}`}><span>{date.getDate()}</span>{date.getDay() > 0 && date.getDay() < 6 && <span className={`mx-auto mt-1 block size-1 rounded-full ${date.toDateString() === selectedDate.toDateString() ? 'bg-white' : 'bg-indigo-500'}`} />}</button> : <span key={`empty-${index}`} />)}</div></section>
    <aside className="border-t border-slate-200 bg-slate-50 p-6 lg:border-l lg:border-t-0"><h2 className="text-xl font-bold">{selectedDate.toLocaleDateString('en-US', { weekday: 'long' })}</h2><p className="mt-1 text-sm text-slate-500">{formatDate(selectedDate)}</p>{!available ? <div className="mt-8 rounded-xl bg-white p-4 text-center text-sm text-slate-500">No availability on this day.</div> : <div className="mt-6 flex max-h-[330px] flex-col gap-2 overflow-y-auto pr-1">{slots.map((slot) => <button key={slot} onClick={() => setSelectedSlot(slot)} className={`rounded-xl border bg-white py-3 text-sm font-semibold transition hover:border-indigo-600 hover:bg-indigo-50 ${selectedSlot === slot ? 'border-indigo-600 bg-indigo-600 text-white hover:bg-indigo-600' : 'border-slate-200 text-indigo-700'}`}>{slot}</button>)}</div>}{selectedSlot && <Button onClick={() => setConfirmed(false)} className="mt-4 w-full rounded-xl bg-indigo-600 hover:bg-indigo-700">Continue</Button>}</aside>
  </div>{selectedSlot && <BookingDialog slot={selectedSlot} date={selectedDate} duration={duration} title={title} confirmed={confirmed} setConfirmed={setConfirmed} studentName={studentName} setStudentName={setStudentName} studentEmail={studentEmail} setStudentEmail={setStudentEmail} />}</div>
}

function BookingDialog({ slot, date, duration, title, confirmed, setConfirmed, studentName, setStudentName, studentEmail, setStudentEmail }: any) { const [open, setOpen] = useState(true); if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl sm:p-8">{confirmed ? <div className="py-6 text-center"><div className="mx-auto grid size-14 place-items-center rounded-full bg-emerald-100 text-emerald-600"><Check /></div><h2 className="mt-5 text-2xl font-bold">You’re booked!</h2><p className="mt-2 text-slate-500">Your session is on the calendar. We sent the details to {studentEmail || 'your inbox'}.</p><div className="mt-6 flex gap-2"><Button variant="outline" className="flex-1"><Link2 className="mr-2 size-4" />Google Calendar</Button><Button variant="outline" className="flex-1">Download iCal</Button></div><Button className="mt-3 w-full bg-indigo-600" onClick={() => setOpen(false)}>Done</Button></div> : <><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-indigo-600">Almost there</p><h2 className="mt-1 text-2xl font-bold">Confirm your session</h2></div><button aria-label="Close booking dialog" onClick={() => setOpen(false)} className="rounded-lg p-2 hover:bg-slate-100"><X className="size-5" /></button></div><div className="mt-5 rounded-xl bg-indigo-50 p-4"><p className="font-bold">{title}</p><p className="mt-1 text-sm text-indigo-900">{date.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })} at {slot} · {duration}</p><p className="mt-1 text-sm text-indigo-800">With Alex Morgan · Zoom</p></div><div className="mt-5 grid gap-4"><label className="text-sm font-semibold">Your name<input value={studentName} onChange={(event) => setStudentName(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal outline-none focus:border-indigo-500" placeholder="Jamie Lee" /></label><label className="text-sm font-semibold">Email address<input type="email" value={studentEmail} onChange={(event) => setStudentEmail(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal outline-none focus:border-indigo-500" placeholder="jamie@example.com" /></label><label className="text-sm font-semibold">Topic or notes<textarea rows={3} className="mt-2 w-full resize-none rounded-xl border border-slate-200 p-3 font-normal outline-none focus:border-indigo-500" placeholder="What would you like to work on?" /></label></div><Button disabled={!studentName || !studentEmail} onClick={() => setConfirmed(true)} className="mt-6 w-full rounded-xl bg-indigo-600 py-3 hover:bg-indigo-700">Confirm booking</Button></>}</div></div> }

export function StudentCalendar({ profileName }: { profileName: string }) { return <SchedulingModule profileName={profileName} initialRole="student" /> }
export function TeacherCalendar({ profileName }: { profileName: string }) { return <SchedulingModule profileName={profileName} initialRole="teacher" /> }
                        
